# Generated by Django 3.1.7 on 2021-03-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(verbose_name='creation_date')),
                ('feeling', models.CharField(choices=[('HA', 'Happy'), ('SA', 'Sad'), ('AN', 'Angry'), ('CO', 'Confident'), ('SI', 'Sick'), ('AM', 'Amazed')], max_length=2)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to=None, verbose_name='photo')),
            ],
        ),
    ]
