# Generated by Django 3.1.7 on 2021-03-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='photo',
            field=models.ImageField(null=True, upload_to=None, verbose_name='photo'),
        ),
    ]
