# Generated by Django 3.1.7 on 2021-03-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210330_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_part', models.TextField(verbose_name='text')),
                ('date_part', models.DateField(verbose_name='date')),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='feeling',
            field=models.CharField(choices=[('HA', 'Happy'), ('SA', 'Sad'), ('AN', 'Angry'), ('CO', 'Confident'), ('SI', 'Sick'), ('AM', 'Amazed')], max_length=2, verbose_name='feeling'),
        ),
    ]
