# Generated by Django 3.1.7 on 2021-03-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210330_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='creation_date'),
        ),
    ]
