# Generated by Django 3.1.7 on 2021-04-02 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210401_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='time_stamp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='creation_date',
            field=models.DateField(verbose_name='creation_date'),
        ),
    ]
